make:
	bison -d 2005021.y
	flex 2005021.l
	g++ 2005021.tab.c lex.yy.c
	./a.out input.c
run:
	./a.out input.c

exp:
	bison -d 2005021.y
	flex 2005021.l
	g++ 2005021.tab.c lex.yy.c
	./a.out ../input/exp.c

func:
	bison -d 2005021.y
	flex 2005021.l
	g++ 2005021.tab.c lex.yy.c
	./a.out ../input/func.c

bonustest1:
	bison -d 2005021.y
	flex 2005021.l
	g++ 2005021.tab.c lex.yy.c
	./a.out ../input/bonustest1_i.c

bonustest2:
	bison -d 2005021.y
	flex 2005021.l
	g++ 2005021.tab.c lex.yy.c
	./a.out ../input/bonustest2_i.c

loop:
	bison -d 2005021.y
	flex 2005021.l
	g++ 2005021.tab.c lex.yy.c
	./a.out ../input/loop.c

test1:
	bison -d 2005021.y
	flex 2005021.l
	g++ 2005021.tab.c lex.yy.c
	./a.out ../input/test1_i.c

test2:
	bison -d 2005021.y
	flex 2005021.l
	g++ 2005021.tab.c lex.yy.c
	./a.out ../input/test2_i.c

test3:
	bison -d 2005021.y
	flex 2005021.l
	g++ 2005021.tab.c lex.yy.c
	./a.out ../input/test3_i.c

test4:
	bison -d 2005021.y
	flex 2005021.l
	g++ 2005021.tab.c lex.yy.c
	./a.out ../input/test4_i.c

test5:	
	bison -d 2005021.y
	flex 2005021.l
	g++ 2005021.tab.c lex.yy.c
	./a.out ../input/test5_i.c

test6:
	bison -d 2005021.y
	flex 2005021.l
	g++ 2005021.tab.c lex.yy.c
	./a.out ../input/test6_i.c

test7:
	bison -d 2005021.y
	flex 2005021.l
	g++ 2005021.tab.c lex.yy.c
	./a.out ../input/test7_i.c

test:
	./a.out ../Test/input.c

clean:
	rm -f a y.tab.c y.tab.h lex.yy.c y.o l.o *.o *.out *.txt *.output 2005021.tab.c 2005021.tab.h parser.c parser.h scanner.c scanner.h
